spring:
  application:
    name: device-service
  datasource:
    url: jdbc:postgresql://localhost:5432/telecom_connect
    username: telecom
    password: telecom
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    table: flyway_schema_history_device

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info
