spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/telecom_connect
    username: telecom
    password: telecom
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    table: flyway_schema_history_subscription
