spring:
  application:
    name: subscription-service
  datasource:
    url: jdbc:postgresql://localhost:5432/telecom_connect
    username: telecom
    password: telecom
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    table: flyway_schema_history_subscription

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info
